language: python
#sudo: false
python:
- '2.7'
- '3.7'
install:
- pip install -r requirements.txt
script:
- tox --recreate
- pytest --cov=./ --cov=--cov-report=term-missing tests
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password: $PYPI_DEPLOY_TOKEN
  on:
    branch: master
    python: 3.7
  skip_existing: true
